### PR TITLE
Adds React / TypeScript / Webpack bundling for frontend development

### LINKED ISSUE #3: Create Front-end Structure
Front-end structure following design in design doc.

### PR DESCRIPTION
**Pull request by jimmycolema**

### CODE REVIEW

**Comment by JosephBushagour** [comment]
Is there any reason that /frontend leads to /react-webpack-typescript-starter and nothing else? If not, I propose all the files from /react-webpack-typescript-starter be moved directly to /frontend; that way we could avoid an extraneous folder nesting.

**Review by linamontes10-zz — APPROVED** [review]

**Comment by JosephBushagour** [comment]
You can remove yarn.lock because we're using npm rather than yarn

**Review by JosephBushagour — COMMENTED** [review]
You can remove yarn.lock because we are using npm rather than yarn

**Comment by KeatonTech** [comment]
Add `node_modules` to the `.gitignore` file and make sure nothing in there gets committed.

**Pull request merged**
